export const DEFAULT_CATEGORIES: Record<string, string[]> = {
  'fashion-shop': [
    "Men's Wear",
    "Women's Wear",
    "Kids & Baby",
    "Accessories",
    "Footwear",
    "Sportswear",
  ],
  'restaurant': [
    "Appetizers",
    "Main Course",
    "Desserts",
    "Beverages",
    "Specials",
    "Sides",
  ],
  'salon': [
    "Hair Services",
    "Nail Services",
    "Skin Care",
    "Makeup",
    "Packages",
    "Products",
  ],
  'pharmacy': [
    "Prescription",
    "OTC Medicine",
    "Vitamins & Supplements",
    "Medical Equipment",
    "Personal Care",
    "Baby Care",
  ],
  'supermarket': [
    "Fresh Produce",
    "Dairy & Eggs",
    "Meat & Seafood",
    "Bakery",
    "Beverages",
    "Snacks & Confectionery",
    "Household",
  ],
  'electronics-shop': [
    "Mobile Phones",
    "Laptops & Computers",
    "Accessories",
    "Audio & Video",
    "Gaming",
    "Smart Home",
  ],
  'general': [
    "General",
  ],
};